3 121 look up table for public transport search interfaces
cgurtner/PROG2-P05 pull request #5
Opened 2022-05-05 13:22 UTC by seitzm97

Issue resolved. See comments in the script, most APIs are not available and usefull for our purpose.

2022-05-05 15:05 UTC, cgurtner commented on lookuptable.py
> +        self.lookuptable = {
This variable could be changed into a constant. It doesn't need to be appended to the instance `self.`.  Furthermore the code indentations isn't uniform.

2022-05-05 15:08 UTC, cgurtner commented on lookuptable.py
> +class Lookuptable:
Is Lookuptable an ideal name? I would suggest a name that implicitly says what it contains. E.g. `PublicTransportInterfaces` or `PubliTransportURL` or something like that.

2022-05-05 15:13 UTC, cgurtner requested changes
review done

2022-05-05 15:13 UTC, cgurtner commented on lookuptable.py
> +    lookuptable = Lookuptable()
Please add a method to retrieve the data for a specific country. In the end we should be able to import this class, create the instance of it and do something like `urls = lookuptable.get_data('ik'); urls['ui']`.

2022-05-05 15:13 UTC, cgurtner commented on lookuptable.py
> +        self.lookuptable = {
This variable could be changed into a constant. It doesn't need to be appended to the instance self.. Furthermore the code indentations isn't uniform.

2022-05-05 15:13 UTC, cgurtner commented on lookuptable.py
> +class Lookuptable:
Is Lookuptable an ideal name? I would suggest a name that implicitly says what it contains. E.g. `PublicTransportInterfaces` or `PubliTransportURL` or something like that.

2022-05-07 12:31 UTC, seitzm97 commented on lookuptable.py
> +    lookuptable = Lookuptable()
2 methods added, one to retrieve the URL and one to open said URL. See testing in script.

2022-05-07 12:31 UTC, seitzm97 commented on lookuptable.py
> +        self.lookuptable = {
Table has been changed in to a constant.

2022-05-07 12:32 UTC, seitzm97 commented on lookuptable.py
> +class Lookuptable:
Name has been changed

2022-05-07 12:34 UTC, merged

2022-05-11 09:18 UTC, cgurtner reviewed
submit